SET 
  ANSI_NULLS, 
  QUOTED_IDENTIFIER, 
  CONCAT_NULL_YIELDS_NULL, 
  ANSI_WARNINGS, 
  ANSI_PADDING 
ON;

use master;

DECLARE @DRIVE VARCHAR(1) = $(DRIVE)
DECLARE @PATH VARCHAR(MAX) = @DRIVE + ':\' + $(PATH)

SET @PATH = REPLACE(@PATH, '%20', ' ');

DECLARE @sql VARCHAR(MAX) = 
'IF (DB_ID(''OraQ'') IS NOT NULL)
	DROP DATABASE OraQ;

CREATE DATABASE OraQ ON
PRIMARY 
(
	NAME=OraQ,
	FILENAME = ''' + @PATH + '\db.mdf''
),
FILEGROUP fsGroup CONTAINS FILESTREAM
(
	NAME = fStream,
	FILENAME = ''' + @PATH + '\file''
)
LOG ON
(
	NAME = OraQLog,
	FILENAME = ''' + @PATH + '\log.ldf''
);'
EXEC(@sql)