SET 
  ANSI_NULLS, 
  QUOTED_IDENTIFIER, 
  CONCAT_NULL_YIELDS_NULL, 
  ANSI_WARNINGS, 
  ANSI_PADDING 
ON;

USE OraQ;
IF OBJECT_ID('goImageData') IS NOT NULL
	DROP PROCEDURE goImageData;
GO

CREATE PROCEDURE goImageData
	@uid NVARCHAR(100)
AS
	SELECT CAST(data AS IMAGE) data
	FROM Inspect.imageData
	WHERE uid = @uid
GO