SET 
  ANSI_NULLS, 
  QUOTED_IDENTIFIER, 
  CONCAT_NULL_YIELDS_NULL, 
  ANSI_WARNINGS, 
  ANSI_PADDING 
ON;

USE OraQ;
IF (OBJECT_ID('mergeDepartment') IS NOT NULL)		DROP PROCEDURE mergeDepartment;
IF (TYPE_ID('DEPARTMENT_MERGE_TABLE') IS NOT NULL)	DROP TYPE DEPARTMENT_MERGE_TABLE;

CREATE TYPE DEPARTMENT_MERGE_TABLE AS TABLE
(
	uid INT NULL,
	name NVARCHAR(100)
)
GO
CREATE PROCEDURE mergeDepartment
	@table DEPARTMENT_MERGE_TABLE READONLY
AS
	DELETE FROM Hospital.department
	WHERE uid NOT IN 
		(SELECT uid FROM @table WHERE uid IS NOT NULL)

	MERGE Hospital.department D
		USING @table M
		ON (D.uid = M.uid)
	WHEN MATCHED THEN
		UPDATE SET D.name = M.name
	WHEN NOT MATCHED THEN
		INSERT VALUES (M.name);
GO