SET 
  ANSI_NULLS, 
  QUOTED_IDENTIFIER, 
  CONCAT_NULL_YIELDS_NULL, 
  ANSI_WARNINGS, 
  ANSI_PADDING 
ON;

USE OraQ;
IF (OBJECT_ID('mergeMWLServer') IS NOT NULL)		DROP PROCEDURE mergeMWLServer
IF (TYPE_ID('MWL_SERVER_MERGE_TABLE') IS NOT NULL)	DROP TYPE MWL_SERVER_MERGE_TABLE
GO

CREATE TYPE MWL_SERVER_MERGE_TABLE AS TABLE
(
	name NVARCHAR(100) PRIMARY KEY,
	aeTitle NVARCHAR(100),
	ip NVARCHAR(100),
	port INT
)
GO

CREATE PROCEDURE mergeMWLServer
	@table MWL_SERVER_MERGE_TABLE READONLY
AS
	--DELETE NOT INCLUDED IN PARAMETER TABLE
	DELETE FROM Server.mwlServer
		WHERE name NOT IN (SELECT name FROM @table);

	--INSERT OR REPLACE INTO EXTERNAL_SERVER
	MERGE Server.externalServer E
		USING @table T
		ON E.name = T.name
	WHEN MATCHED THEN
		UPDATE SET E.aeTitle = T.aeTitle, E.ip = T.ip, E.port = T.port
	WHEN NOT MATCHED THEN
		INSERT VALUES (T.name, T.aeTitle, T.ip, T.port);

	--INSERT OR REPLACE INTO PACS_SERVER
	MERGE Server.mwlServer P
		USING @table T
		ON P.name = T.name
	WHEN NOT MATCHED THEN
		INSERT VALUES (T.name);
GO