SET 
  ANSI_NULLS, 
  QUOTED_IDENTIFIER, 
  CONCAT_NULL_YIELDS_NULL, 
  ANSI_WARNINGS, 
  ANSI_PADDING 
ON;

Use OraQ;
IF OBJECT_ID('goError') IS NOT NULL
	DROP PROCEDURE goError
GO

CREATE PROCEDURE goError
AS
	SELECT * FROM INVALID_TABLE;
GO