package samchon.protocol.movie
{
	import mx.managers.PopUpManager;
	
	import samchon.library.ui.TitleWindow;
	import samchon.protocol.invoke.IProtocol;
	import samchon.protocol.invoke.Invoke;
	
	/**
	 * SubMovieTitleWindow is generated by SubMovie<br/>
	 * 
	 * @copy org.samchon.library.ui.TitleWindow 
	 */ 
	public class SubMovieTitleWindow 
		extends TitleWindow 
		implements IProtocol
	{
		/**
		 * Parent SubMovie who made this <code>SubMovieTitleWindow</code>
		 */
		protected var subMovie:SubMovie;
		
		/**
		 * Constructor.<br/>
		 * <br/>
		 * @param window Parent SubMovie who made this SubMovieTitleWindow
		 */
		public function SubMovieTitleWindow(subMovie:SubMovie = null)
		{
			super();
			
			this.subMovie = subMovie;
		}
		
		public function sendData(invoke:Invoke):void
		{
			subMovie.sendData(invoke);
		}
		public function replyData(invoke:Invoke):void
		{
		}
		
		/**
		 * Static factory method for SubMovieTitleWindow<br/>
		 * Do not recommend to create SubMovieTitleWindow by this. Use each createPopUp method in SubMovie<br/>
		 * <br/>
		 * 
		 * @param subMovie Parent SubMovie
		 * @param $class Target SubMovieTitleWindow class to create
		 * 
		 * @see SubMovie
		 */
		public static function createPopUp(subMovie:SubMovie, $class:Class):SubMovieTitleWindow
		{
			var popUp:SubMovieTitleWindow = PopUpManager.createPopUp(subMovie, $class, true) as SubMovieTitleWindow;
			popUp.subMovie = subMovie;
			PopUpManager.centerPopUp(popUp);
			
			return popUp;
		}
	}
}