CREATE TABLE board
(
	uid		INT		PRIMARY KEY	auto_increment,
	pid		INT		NOT NULL,
	application	SMALLINT	NOT NULL,
	category	SMALLINT	NOT NULL,

	id		VARCHAR(60)	NOT NULL,
	title		VARCHAR(120)	NOT NULL,
	content		TEXT,
	timestamp	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	hit		INT		NOT NULL	DEFAULT 0,

	depth		VARCHAR(255)	NOT NULL	DEFAULT 'A',
	live		SMALLINT	NOT NULL	DEFAULT 1,

	INDEX pid(pid)
);